services:
  back:
    build:
      context: ./back
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
      - ./back/uploads:/app/uploads
    environment:
      - MONGO_URL=${MONGO_URL}
      - AI_API_KEY=${AI_API_KEY}
      - AI_URL=${AI_URL}
    depends_on:
      - mongo

  front:
    build:
      context: ./front
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_IMAGE_URL=${NEXT_PUBLIC_IMAGE_URL}
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_IMAGE_URL=${NEXT_PUBLIC_IMAGE_URL}
    depends_on:
      - back

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
