name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        working-directory: ./back
        run: |
          pipenv install --dev

      - name: Run pytest
        working-directory: ./back
        env:
          MONGO_URL: mongodb://localhost:27017
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
        run: |
          pipenv run pytest -v

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: ./back/pytest-report.xml
          if-no-files-found: ignore